version: 0.1
environment_variables:
  plaintext:
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing yarn
      - npm install -g yarn

      - echo Installing source NPM dependencies...
      - yarn
  pre_build:
    commands:
      - npm run lint
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
