version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "angular6-demo-api"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo Installing yarn
      - npm install -g yarn

      - echo Installing source NPM dependencies...
      - yarn
  pre_build:
    commands:
      - npm run lint
  build:
    commands:
      - echo No build required
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
